import test from 'node:test';
import assert from 'node:assert/strict';
import { inflateSync } from 'node:zlib';
import { compose, protectionMask, bounds, geometry, rasterHash, recipe, parseRecipe, zones, adjustments, History, DEFAULTS } from '../../dist/compiled/packages/looklock/core.js';
import { encodePNG } from '../../dist/compiled/packages/looklock/png.js';
function frame(w=12,h=8,offset=0) {const data=new Uint8ClampedArray(w*h*4);for(let i=0;i<data.length;i++)data[i]=(i*23+offset)%256;return {width:w,height:h,data};}
const rect={id:'r1',label:'HUD',x:.25,y:.25,width:.5,height:.5};
function decodePNG(buffer){assert.deepEqual([...buffer.subarray(0,8)],[137,80,78,71,13,10,26,10]);let p=8,w,h,idats=[];
 while(p<buffer.length){const n=buffer.readUInt32BE(p),type=buffer.toString('ascii',p+4,p+8),data=buffer.subarray(p+8,p+8+n);let crc=0xffffffff;for(const byte of buffer.subarray(p+4,p+8+n)){crc^=byte;for(let j=0;j<8;j++)crc=(crc&1)?0xedb88320^(crc>>>1):crc>>>1;}assert.equal((crc^0xffffffff)>>>0,buffer.readUInt32BE(p+8+n));
  if(type==='IHDR'){w=data.readUInt32BE(0);h=data.readUInt32BE(4);assert.equal(data[8],8);assert.equal(data[9],6);}if(type==='IDAT')idats.push(data);p+=12+n;}
 const raw=inflateSync(Buffer.concat(idats)),pixels=[];assert.equal(raw.length,(w*4+1)*h);for(let y=0;y<h;y++){assert.equal(raw[y*(w*4+1)],0);pixels.push(raw.subarray(y*(w*4+1)+1,(y+1)*(w*4+1)));}return {w,h,data:Buffer.concat(pixels)};}
test('LookLock zero/full blend endpoints preserve every RGBA byte without source mutation',()=>{const a=frame(),b=frame(12,8,41),copy=a.data.slice();assert.deepEqual(compose(a,b,[],{...DEFAULTS,blend:0}).output.data,a.data);assert.deepEqual(compose(a,b,[],{...DEFAULTS,blend:1}).output.data,b.data);assert.deepEqual(a.data,copy);});
test('LookLock all protected core pixels remain exact including alpha and hidden colors',()=>{const a=frame(),b=frame(12,8,91),r=compose(a,b,[rect],DEFAULTS);assert.equal(r.metrics.protectedPixels,24);assert.equal(r.metrics.protectedMismatches,0);for(let y=2;y<6;y++)for(let x=3;x<9;x++)assert.deepEqual(r.output.data.slice((y*12+x)*4,(y*12+x)*4+4),a.data.slice((y*12+x)*4,(y*12+x)*4+4));});
test('LookLock feather extends outside rather than eroding the core',()=>{const hard=protectionMask(12,8,[rect],0),soft=protectionMask(12,8,[rect],2);for(let i=0;i<hard.length;i++)if(hard[i]===255)assert.equal(soft[i],255);assert(soft[1*12+3]>0&&soft[1*12+3]<255);assert.equal(hard[1*12+3],0);});
test('LookLock overlapping zones form a union and do not double-count protected pixels',()=>{const first={...rect,x:0,y:0,width:.5,height:1},second={...rect,id:'r2',x:.25,y:0,width:.5,height:1};const r=compose(frame(),frame(12,8,9),[first,second],{...DEFAULTS,feather:0});assert.equal(r.metrics.protectedPixels,72);assert.equal(r.metrics.protectedMismatches,0);});
test('LookLock normalized integer raster edges do not drift at 1080p or odd dimensions',()=>{for(const [w,h] of [[1920,1080],[997,631]]){const z={...rect,x:19/w,y:37/h,width:101/w,height:59/h};assert.deepEqual(bounds(z,w,h),{x:19,y:37,right:120,bottom:96});}});
test('LookLock fractional normalized rectangles snap outward and clip to valid edge',()=>{assert.deepEqual(bounds({...rect,x:.11,y:.11,width:.21,height:.21},10,10),{x:1,y:1,right:4,bottom:4});});
test('LookLock blend interpolates premultiplied colors to avoid transparent edge halos',()=>{const a={width:1,height:1,data:new Uint8ClampedArray([255,0,0,0])},b={width:1,height:1,data:new Uint8ClampedArray([0,0,255,255])};assert.deepEqual([...compose(a,b,[],{...DEFAULTS,blend:.5}).output.data],[0,0,255,128]);});
test('LookLock raw difference threshold and protected differences have separate meanings',()=>{const a={width:2,height:1,data:new Uint8ClampedArray([10,20,30,255,20,30,40,255])},b={width:2,height:1,data:new Uint8ClampedArray([18,20,30,255,21,30,40,255])};const r=compose(a,b,[{...rect,x:0,y:0,width:.5,height:1}],{...DEFAULTS,feather:0,threshold:8});assert.equal(r.metrics.rawChanged,1);assert.equal(r.metrics.outputChanged,0);assert.equal(r.metrics.protectedMismatches,0);assert.equal(r.heatmap.data[3],255);});
test('LookLock rejects mismatched dimensions, truncated buffers, unsafe geometry',()=>{assert.throws(()=>compose(frame(),frame(11,8),[],DEFAULTS),/identical dimensions/);assert.throws(()=>compose({...frame(),data:new Uint8ClampedArray(1)},frame(),[],DEFAULTS),/RGBA/);for(const dims of [[0,10],[-1,10],[NaN,10],[Infinity,10],[1.5,2],[4097,1],[3000,3000]])assert.throws(()=>geometry(...dims));});
test('LookLock rejects untrusted region schema, duplicate IDs, overflow, unsafe numbers',()=>{for(const value of [null,{},[null],[{...rect,x:-.1}],[{...rect,width:NaN}],[{...rect,x:.8}],[{...rect,label:'bad\nname'}],[{...rect,id:'../../file'}],[{...rect,path:'/file'}],[rect,rect],Array.from({length:25},(_,i)=>({...rect,id:`r${i}`}))])assert.throws(()=>zones(value));});
test('LookLock rejects out-of-range settings and preserves immutable defaults',()=>{for(const value of [{...DEFAULTS,blend:NaN},{...DEFAULTS,feather:1.5},{...DEFAULTS,feather:65},{...DEFAULTS,threshold:0},{...DEFAULTS,shell:'run'}])assert.throws(()=>adjustments(value));assert(Object.isFrozen(DEFAULTS));});
test('LookLock pixel fingerprint includes dimensions, is stable, and detects a one-byte edit',async()=>{const a=frame(),b=frame();assert.equal(await rasterHash(a),await rasterHash(b));b.data[0]^=1;assert.notEqual(await rasterHash(a),await rasterHash(b));assert.notEqual(await rasterHash(a),await rasterHash({...a,width:8,height:12}));});
test('LookLock recipe round-trips and only loads for the exact decoded pair',async()=>{const identity={width:12,height:8,sourceHash:await rasterHash(frame()),candidateHash:await rasterHash(frame(12,8,1))},r=recipe(identity,[rect],DEFAULTS);assert.deepEqual(parseRecipe(JSON.stringify(r),identity),r);for(const key of ['sourceHash','candidateHash'])assert.throws(()=>parseRecipe(JSON.stringify(r),{...identity,[key]:'f'.repeat(64)}),/different decoded/);assert.throws(()=>parseRecipe(JSON.stringify({...r,exec:'x'}),identity));assert.throws(()=>parseRecipe(' '.repeat(32769),identity));});
test('LookLock history restores removed locks and invalidates stale redo branch',()=>{const h=new History([],2);h.set([rect]);h.set([]);h.undo();assert.equal(h.value[0].id,'r1');h.redo();assert.equal(h.value.length,0);h.undo();h.set([{...rect,id:'r2'}]);assert(!h.canRedo);h.undo();h.undo();h.undo();assert.equal(h.value.length,0);});
test('LookLock lossless PNG independently decodes exact RGBA including zero-alpha colors',async()=>{const a=frame(11,7);const decoded=decodePNG(Buffer.from(await encodePNG(a).arrayBuffer()));assert.equal(decoded.w,11);assert.equal(decoded.h,7);assert.deepEqual(decoded.data,Buffer.from(a.data));});
test('LookLock PNG handles multiple DEFLATE blocks and CRC/Adler checksums',async()=>{const a=frame(321,180),decoded=decodePNG(Buffer.from(await encodePNG(a).arrayBuffer()));assert.deepEqual(decoded.data,Buffer.from(a.data));});
test('LookLock exported protected PNG is still exact after independent PNG decoding',async()=>{const a=frame(321,180),b=frame(321,180,31),r=compose(a,b,[rect],DEFAULTS);const decoded=decodePNG(Buffer.from(await encodePNG(r.output).arrayBuffer()));for(let p=0;p<r.mask.length;p++)if(r.mask[p]===255)assert.deepEqual(decoded.data.subarray(p*4,p*4+4),Buffer.from(a.data.subarray(p*4,p*4+4)));});
test('LookLock randomized rectangles always preserve their complete protected core',()=>{let seed=571;for(let t=0;t<30;t++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const x=seed%15,y=(seed>>>8)%10;const z={...rect,x:x/31,y:y/23,width:(1+seed%12)/31,height:(1+(seed>>>4)%8)/23};const r=compose(frame(31,23,t),frame(31,23,t+20),[z],{...DEFAULTS,feather:t%12,blend:(t%10)/10});assert.equal(r.metrics.protectedMismatches,0);}});
